// <auto-generated />
using LojaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LojaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629120159_AtualizacaoModelo")]
    partial class AtualizacaoModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoriaProduto", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriasId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("CategoriaProduto");

                    b.HasData(
                        new
                        {
                            CategoriasId = 1,
                            ProdutosId = 1
                        },
                        new
                        {
                            CategoriasId = 3,
                            ProdutosId = 1
                        },
                        new
                        {
                            CategoriasId = 2,
                            ProdutosId = 2
                        },
                        new
                        {
                            CategoriasId = 2,
                            ProdutosId = 3
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Periféricos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Notebooks"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "Dell",
                            Nome = "Notebook",
                            Preco = 3500m,
                            SKU = "SKNOTE11909"
                        },
                        new
                        {
                            Id = 2,
                            Marca = "Logitech",
                            Nome = "Mouse",
                            Preco = 150m,
                            SKU = "SKMOUSE1190119"
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Logitech",
                            Nome = "Teclado",
                            Preco = 350m,
                            SKU = "SKKEYBRD1122909"
                        });
                });

            modelBuilder.Entity("CategoriaProduto", b =>
                {
                    b.HasOne("LojaApi.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaApi.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
