// <auto-generated />
using LojaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CategoriaProduto", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriasId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("CategoriaProduto");

                    b.HasData(
                        new
                        {
                            CategoriasId = 1,
                            ProdutosId = 1
                        },
                        new
                        {
                            CategoriasId = 3,
                            ProdutosId = 1
                        },
                        new
                        {
                            CategoriasId = 2,
                            ProdutosId = 2
                        },
                        new
                        {
                            CategoriasId = 2,
                            ProdutosId = 3
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Periféricos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Notebooks"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "Dell",
                            Nome = "Notebook",
                            Preco = 3500m,
                            SKU = "SKNOTE11909"
                        },
                        new
                        {
                            Id = 2,
                            Marca = "Logitech",
                            Nome = "Mouse",
                            Preco = 150m,
                            SKU = "SKMOUSE1190119"
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Logitech",
                            Nome = "Teclado",
                            Preco = 350m,
                            SKU = "SKKEYBRD1122909"
                        });
                });

            modelBuilder.Entity("CategoriaProduto", b =>
                {
                    b.HasOne("LojaApi.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaApi.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
